// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package app

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjson924c9c66DecodeGithubComZztkmZztkmBbsApp(in *jlexer.Lexer, out *HelloResponse) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "message":
			out.Message = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson924c9c66EncodeGithubComZztkmZztkmBbsApp(out *jwriter.Writer, in HelloResponse) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"message\":"
		out.RawString(prefix[1:])
		out.String(string(in.Message))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v HelloResponse) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson924c9c66EncodeGithubComZztkmZztkmBbsApp(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v HelloResponse) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson924c9c66EncodeGithubComZztkmZztkmBbsApp(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *HelloResponse) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson924c9c66DecodeGithubComZztkmZztkmBbsApp(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *HelloResponse) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson924c9c66DecodeGithubComZztkmZztkmBbsApp(l, v)
}
